#ifndef SERVER_REPLY_H
#define SERVER_REPLY_H

#define SERVER_REPLY_OK 0x4f4b     // 'OK'
#define SERVER_REPLY_ERROR 0x4552  // 'ER'

#define SERVER_REPLY_ERROR_NOT_FOUND 0x4e46  // 'NF'
#define SERVER_REPLY_ERROR_NEVER_RUN 0x4e52  // 'NR'

#endif // SERVER_REPLY_H
